// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB7LhoLiiSC7z68m4UDLMjsawFSeBIfRo',
    appId: '1:573311220969:web:ad60e398d28a3f1eac0478',
    messagingSenderId: '573311220969',
    projectId: 'conn-d2504',
    authDomain: 'conn-d2504.firebaseapp.com',
    storageBucket: 'conn-d2504.appspot.com',
    measurementId: 'G-LFSFDVLB7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBUGCxqmx-dRGi9Sp-A3zIgD5LzukBPpM',
    appId: '1:573311220969:android:be1e420882c09268ac0478',
    messagingSenderId: '573311220969',
    projectId: 'conn-d2504',
    storageBucket: 'conn-d2504.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw-oOninlVXDfw4eo0a_AQNewAmejcED0',
    appId: '1:573311220969:ios:114aef3a445b051fac0478',
    messagingSenderId: '573311220969',
    projectId: 'conn-d2504',
    storageBucket: 'conn-d2504.appspot.com',
    androidClientId: '573311220969-v7r6fjlkh54gfpbhg56ebmrgl7i29tl0.apps.googleusercontent.com',
    iosClientId: '573311220969-uotp0a4dgu919vgq60unmcl4mlsb7b60.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

}